### PR TITLE
471 as standalone app

### LINKED ISSUE #471: Standalone installation of pricing service
Add the ability to install each Storefront Service as a standalone application 

AC:
* service may depend only on Magento Framework 
* own composer.json configuration to install service 
* CLI command to setup service (resources to DB, connections, etc...)
* global di.xml should have minimum preferences/configuration to handle 
** configure grpc command storefront:grpc:init
** run of gRPC service via ./vendor/bin/grpc-server
** run "setup" service command
* README.md file provide sufficient documentation on how to setup and use service

Repo: https://github.com/magento/storefront-pricing-ce

See an example of init command in storefront-search-ce repo Magento_SearchStorefrontConfig console command

### PR DESCRIPTION
**Pull request by lykhachov**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/catalog-storefront/issues/471

### Code Review Checklist (*)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
- [ ] no backward incompatible changes

### CODE REVIEW

**Comment by lykhachov** [comment]
@magento run all tests

**Comment by lykhachov** [comment]
@magento run all tests

**Comment by lykhachov** [comment]
@magento run all tests

**Comment by lykhachov** [comment]
@magento run Static Tests

**Comment by lykhachov** [comment]
@magento run Static Tests

**Comment by lykhachov** [comment]
@magento run all tests

**Comment by mslabko** [comment]
@magento import pr to magento-commerce/storefront-pricing-ce

**Comment by magento-engcom-team** [comment]
@mslabko the pull request successfully imported.

**Pull request closed without merging**
